#to encode in base64 the password: echo -n <password> | base64
---
apiVersion: v1
kind: Secret
metadata:
  name: flaskapi-secrets
type: Opaque
data:
  db_root_password: # copy here the encoded password #
